name: 'Upload to Lingohub'
description: 'Upload source content files to your Lingohub project for translation. Supports glob patterns and locale configuration.'
author: 'lingohub GmbH'
branding:
  icon: 'upload-cloud'
  color: 'blue'
inputs:
  api_key:
    description: 'Lingohub API key'
    required: true
  project_id:
    description: 'Lingohub project ID'
    required: true
  files:
    description: 'Path or glob pattern to files to upload (e.g. ./locales/*.json)'
    required: true
  locale:
    description: 'Locale option for the files. Use "auto" for automatic detection or specify a locale (e.g., "en").'
    required: false
    default: 'auto'
runs:
  using: 'node16'
  main: 'dist/index.js'
