name: 'Upload to Lingohub'
description: 'Upload source content files to your Lingohub project for translation. Supports glob patterns and automatic locale detection.'
author: 'lingohub GmbH'
branding:
  icon: 'upload-cloud'
  color: 'blue'
inputs:
  api_key:
    description: 'Lingohub API key'
    required: true
  project_id:
    description: 'Lingohub project ID (e.g., pr_18JCETCbSz7e-40731)'
    required: true
  files:
    description: 'Paths or glob pattern to files to upload (e.g. ./locales/*.json)'
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'
